[project]
name = "hello-kuzu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
    "jupyterlab>=4.4.1",
    "kuzu>=0.9.0",
    "marimo>=0.13.2",
]
